### PR TITLE
Update .gitignore, add 'defaults.yml' to stage ansible vars, update stage READMEs to reflect

### PR DESCRIPTION
**Pull request by jwmatthews**

### CODE REVIEW

**Review by djwhatle — APPROVED** [review]

**Comment by djwhatle** [comment]
@jwmatthews let's not merge this as is, currently we have some non-symmetry in stage 3 where https://github.com/konveyor/pvc-migrate/blob/master/3_run_rsync/vars/run-rsync.yml is using `run-rsync.yml` as the authoritative sample file instead of using `run-rsync.yml.sample`. If we merge, the real sample file will be ignored in future commits.

**Comment by djwhatle** [comment]
Going to add a few more changes into this PR and then merge:

1. Fix stage 3 vars file so that sample is authoritative
2. Add `defaults.yml` to hold ansible vars that users won't likely need to modify (need to see if this makes sense in practice, will find out)

**Comment by djwhatle** [comment]
Rebased

**Review by pranavgaikwad — APPROVED** [review]
ACK

**Pull request merged**
