### PR TITLE
run rsync on sshd via node port

### PR DESCRIPTION
**Pull request by alaypatel07**
This PR 
- changes the service from an external load balancer to node port
- removes the DNS lookup on external load balancer dns name
- adds lookup to the node and uses the internal IP address as the destination url

### CODE REVIEW

**Comment by alaypatel07** [comment]
```    
    clusterIP: 172.30.143.211
    externalTrafficPolicy: Cluster
    ports:
    - name: ssh
      nodePort: 31613
      port: 2222
      protocol: TCP
      targetPort: 2222
    selector:
      app: pvc-migrate-bmark0
      owner: pvc-migrate
      purpose: rsync
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
```
The nodeport svc looks like that.

**Comment by alaypatel07** [comment]
```
 32552 -o StrictHostKeyChecking=no -i ~/.ssh/dest_key' root@node2.alpatel-image-3117.internal:/mnt/pvc-migrate-bmark-foo/pvc-0",                                                    [564/36849]
    "delta": "0:00:00.277565",
    "end": "2020-12-15 16:28:42.517913",
    "invocation": {
        "module_args": {
            "_raw_params": "rsync -aPvvH /var/lib/origin/openshift.local.volumes/pods/92f5b3ba-3e81-11eb-be66-0a2534bbbe2f/volumes/kubernetes.io~glusterfs/pvc-92f0efae-3e81-11eb-be66-0a2534b$
be2f/ -e 'ssh -p 32552 -o StrictHostKeyChecking=no -i ~/.ssh/dest_key' root@node2.alpatel-image-3117.internal:/mnt/pvc-migrate-bmark-foo/pvc-0",
            "_uses_shell": true,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 23,
    "start": "2020-12-15 16:28:42.240348",
    "stderr": "Warning: Permanently added '[node2.alpatel-image-3117.internal]:32552,[192.168.0.149]:32552' (ECDSA) to the list of known hosts.\r\nrsync: change_dir \"/var/lib/origin/openshi$
t.local.volumes/pods/92f5b3ba-3e81-11eb-be66-0a2534bbbe2f/volumes/kubernetes.io~glusterfs/pvc-92f0efae-3e81-11eb-be66-0a2534bbbe2f\" failed: Permission denied (13)\nrsync error: some files/a$
trs were not transferred (see previous errors) (code 23) at main.c(1178) [sender=3.1.2]",
    "stderr_lines": [
        "Warning: Permanently added '[node2.alpatel-image-3117.internal]:32552,[192.168.0.149]:32552' (ECDSA) to the list of known hosts.",
        "rsync: change_dir \"/var/lib/origin/openshift.local.volumes/pods/92f5b3ba-3e81-11eb-be66-0a2534bbbe2f/volumes/kubernetes.io~glusterfs/pvc-92f0efae-3e81-11eb-be66-0a2534bbbe2f\" fail$
d: Permission denied (13)",
        "rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1178) [sender=3.1.2]"
    ],
    "stdout": "opening connection using: ssh -p 32552 -o StrictHostKeyChecking=no -i \"~/.ssh/dest_key\" -l root node2.alpatel-image-3117.internal rsync --server -vvlHogDtpre.iLsfxC --partia$
 . /mnt/pvc-migrate-bmark-foo/pvc-0  (16 args)\nsending incremental file list\ndelta-transmission enabled\ntotal: matches=0  hash_hits=0  false_alarms=0 data=0\n\nsent 20 bytes  received 43 $
ytes  126.00 bytes/sec\ntotal size is 0  speedup is 0.00",
    "stdout_lines": [
        "opening connection using: ssh -p 32552 -o StrictHostKeyChecking=no -i \"~/.ssh/dest_key\" -l root node2.alpatel-image-3117.internal rsync --server -vvlHogDtpre.iLsfxC --partial . /m$
t/pvc-migrate-bmark-foo/pvc-0  (16 args)",
        "sending incremental file list",
        "delta-transmission enabled",
        "total: matches=0  hash_hits=0  false_alarms=0 data=0",
        "",
        "sent 20 bytes  received 43 bytes  126.00 bytes/sec",
        "total size is 0  speedup is 0.00"
    ]
}
```

I tried to test this on the same cluster as the source, because of the way pvc-migrate is currently wired, it is expected to fail, but the ssh connection was successful in the blob above

**Review by pranavgaikwad — APPROVED** [review]
ACK

**Review by pranavgaikwad — APPROVED** [review]
ACK

**Pull request merged**
